import type { Generator } from '../../gen'
import type { ZedThemeFamily } from './types'

export const generateZedTheme: Generator<ZedThemeFamily> = (c, unprocessed, name) => ({
	author: 'rautenbergf',
	name: 'Evoke',
	themes: [
		{
			name: `Evoke ${name}`,
			appearance: 'dark',
			style: {
				'status_bar.background': c.bg,
				background: c.bg,
				text: c.gray,
				'text.placeholder': c.grayDarker,
				'text.muted': c.grayDark,
				'text.accent': c.green,
				'element.background': c.bg,
				'editor.gutter.background': c.bg,
				'tab.active_background': c.grayDarker,
				'tab.inactive_background': c.bg,
				'title_bar.background': c.bg,
				'title_bar.inactive_background': c.bg,
				'panel.background': c.bg,
				'tab_bar.background': c.bg,
				'background.appearance': 'opaque',
				'editor.background': c.bg,
				'editor.foreground': c.fg,
				'surface.background': c.bg,
				'elevated_surface.background': c.bg,
				'toolbar.background': c.bg,
				'editor.indent_guide': c.line,
				'editor.indent_guide_active': c.grayDarker,
				'editor.line_number': c.grayDarker,
				'editor.active_line_number': c.gray,
				'editor.hover_line_number': c.grayDark,
				border: c.line,
				'border.focused': c.grayDark,
				'border.selected': c.gray,
				'element.selected': c.grayDarker,
				'element.hover': c.grayDarker,
				accents: [c.green],
				created: `${c.yellow.slice(0, 7)}cc`,
				'created.background': `${c.yellow.slice(0, 7)}3d`,
				deleted: c.red,
				'deleted.background': `${c.red.slice(0, 7)}3d`,
				conflict: c.pink,
				'conflict.background': `${c.pink.slice(0, 7)}3d`,
				ignored: c.grayDark,
				'ignored.background': `${c.grayDark.slice(0, 7)}3d`,
				modified: `${c.cyan.slice(0, 7)}cc`,
				'modified.background': `${c.cyan.slice(0, 7)}3d`,
				'ghost_element.background': '#00000000',
				'ghost_element.hover': '#2d2f34ff',
				'ghost_element.active': '#3e4043ff',
				'ghost_element.selected': '#3e4043ff',
				'ghost_element.disabled': '#1f2127ff',
				'scrollbar.thumb.background': '#ffffff36',
				'scrollbar.thumb.hover_background': '#ffffff50',
				'scrollbar.thumb.border': c.line,
				'scrollbar.track.background': '#00000000',
				'scrollbar.track.border': c.line,
				error: unprocessed.red,
				warning: unprocessed.yellow,
				info: unprocessed.cyan,
				players: [
					{
						cursor: c.green,
						background: c.green,
						selection: `${c.green.slice(0, 7)}3d`,
					},
					{
						cursor: c.orange,
						background: c.orange,
						selection: `${c.orange.slice(0, 7)}3d`,
					},
					{
						cursor: c.pink,
						background: c.pink,
						selection: `${c.pink.slice(0, 7)}3d`,
					},
					{
						cursor: c.cyan,
						background: c.cyan,
						selection: `${c.cyan.slice(0, 7)}3d`,
					},
				],
				syntax: {
					attribute: {
						color: c.gray,
					},
					boolean: { color: c.pink },
					comment: { color: c.grayMid },
					'comment.doc': { color: c.grayMid },
					constant: { color: c.pink },
					enum: { color: c.orange },
					function: { color: c.cyanLight, font_weight: 800 },
					link_text: { color: c.green },
					link_uri: { color: c.pink },
					number: { color: c.pink },
					operator: {
						color: c.green,
					},
					property: {
						color: c.gray,
					},
					punctuation: { color: c.gray },
					string: { color: c.cyan },
					type: { color: c.orange },
					keyword: { color: c.green },
					tag: { color: c.greenDark },
				},
			},
		},
	],
})
